export const CHARACTERS_REQUEST = 'CHARACTERS_REQUEST';
export const CHARACTERS_REQUEST_START = 'CHARACTERS_REQUEST_START';
export const CHARACTERS_REQUEST_FAILURE = 'CHARACTERS_REQUEST_FAILURE';
export const CHARACTERS_REQUEST_SUCCESS = 'CHARACTERS_REQUEST_SUCCESS';